O algoritmo Mean Shift não requer parametrização como o DBSCAN ou o Kmeans.
Cada ponto inicial é considerado um cluster, fazendo os demais pontos convergirem ao ponto de maior densidade.

Vantagens:
 - Funciona com ruído e detecta diversas formas, não apenas radial;

Desvantagens:
 - Não funciona com dados de alta dimensionalidade;
 - Computacionalmente caro.

In [ ]:
!pip install biokit

In [2]:
import plotly.graph_objects as go
import pandas as pd
import numpy as np

In [3]:
url = "https://raw.githubusercontent.com/alura-cursos/Clustering/Aula-1.-An%C3%A1lise-Explorat%C3%B3ria/Wine.csv"

df = pd.read_csv(url)
df.head()

Alcohol  Malic_Acid   Ash  ...  OD280  Proline  Customer_Segment
0    14.23        1.71  2.43  ...   3.92     1065                 1
1    13.20        1.78  2.14  ...   3.40     1050                 1
2    13.16        2.36  2.67  ...   3.17     1185                 1
3    14.37        1.95  2.50  ...   3.45     1480                 1
4    13.24        2.59  2.87  ...   2.93      735                 1

[5 rows x 14 columns]

In [4]:
### Normalização dos dados:

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_normalizado = scaler.fit_transform(df) ## Retorna um numpy Array
df_normalizado = pd.DataFrame(data=df_normalizado, columns=df.keys()) ## Transforma em DataFrame

df_normalizado.describe()

Alcohol    Malic_Acid  ...       Proline  Customer_Segment
count  1.780000e+02  1.780000e+02  ...  1.780000e+02      1.780000e+02
mean  -8.619821e-16 -8.357859e-17  ... -7.484650e-18     -9.056426e-16
std    1.002821e+00  1.002821e+00  ...  1.002821e+00      1.002821e+00
min   -2.434235e+00 -1.432983e+00  ... -1.493188e+00     -1.213944e+00
25%   -7.882448e-01 -6.587486e-01  ... -7.846378e-01     -1.213944e+00
50%    6.099988e-02 -4.231120e-01  ... -2.337204e-01      7.996036e-02
75%    8.361286e-01  6.697929e-01  ...  7.582494e-01      1.373864e+00
max    2.259772e+00  3.109192e+00  ...  2.971473e+00      1.373864e+00

[8 rows x 14 columns]

In [5]:
from sklearn.cluster import MeanShift

agrupador = MeanShift()
agrupador.fit(df)
agrupador.labels_

array([2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 2, 2, 0,
       1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0])

In [6]:
## Gráfico cluster relacionando a intensidade da cor com a quantidade de alcool de cada grupo:

fig = go.Figure()
fig.add_trace(go.Scatter(x = df['Color_Intensity'], y = df['Alcohol'], 
                            mode = 'markers',
                            marker = dict(color = agrupador.labels_.astype(np.float)),
                            text = agrupador.labels_,
                         ))
fig.update_layout(scene = dict(
    xaxis_title = "Intensidade de cor",
    yaxis_title = "Álcool"
))
fig.show()

In [7]:
## Gráfico em 3D:

fig = go.Figure()
fig.add_trace(go.Scatter3d(x = df['Color_Intensity'], y = df['Alcohol'], z = df['Proline'],
                            mode = 'markers',
                            marker = dict(color = agrupador.labels_.astype(np.float)),
                            text = agrupador.labels_
                         ))

fig.update_layout(scene = dict(
    xaxis_title = "Intensidade de cor",
    yaxis_title = "Álcool",
    zaxis_title = "Proline"
))
fig.show()

In [49]:
### Podemos variar um parâmetro do algoritmo Mean Shift, o Bandwidth:

from sklearn.cluster import estimate_bandwidth

bw = estimate_bandwidth(df, quantile = 0.1)
bw ## 63.18

63.180850991985075

In [50]:
agrupador = MeanShift(bandwidth=bw)
agrupador.fit(df)
agrupador.labels_

array([ 4,  4,  8,  9,  5,  9,  7,  7,  4,  4,  9,  7,  7,  8,  9,  7,  7,
        8, 10,  6,  5,  5,  4,  4,  6,  6,  8,  7,  6,  4,  7,  9,  4,  7,
        8,  6,  6,  8,  4,  5,  5,  4,  8,  1,  6,  4,  4,  4,  4,  7,  8,
        7,  8,  7,  4,  8,  4,  7,  7,  0,  1,  3,  1,  3,  3,  1,  0,  0,
        5,  5,  6,  3,  3,  4,  6,  3,  3,  0,  5,  3,  3,  1,  1,  0,  0,
        3,  0,  2,  1,  1,  0,  3,  0,  3,  3,  6,  1,  3,  1,  3,  1,  2,
        3,  3,  1,  3,  0,  0,  3,  1,  2,  3,  2,  3,  3,  3,  0,  3,  3,
        2,  1,  3,  3,  3,  3,  3,  3,  3,  3,  2,  1,  0,  2,  2,  1,  1,
        1,  0,  2,  2,  2,  5,  0,  2,  6,  6,  3,  1,  1,  2,  0,  0,  3,
        1,  1,  5,  0,  6,  1,  1,  0,  1,  2,  1,  1,  0,  1,  1,  5,  1,
        0,  3,  1,  5,  5,  6,  6,  2])

In [51]:
fig = go.Figure()
fig.add_trace(go.Scatter(x = df['Color_Intensity'], y = df['Alcohol'], 
                            mode = 'markers',
                            marker = dict(color = agrupador.labels_.astype(np.float)),
                            text = agrupador.labels_,
                         ))
fig.update_layout(scene = dict(
    xaxis_title = "Intensidade de cor",
    yaxis_title = "Álcool"
))
fig.show()

Quanto menor o bandwidth, mais clusteres o algoritmo irá encontrar.

 - O quantil define a bandwidth.
     - Quantil é a parte da lista ordenada escolhida, quando menor o quantil, mais próximo do inicio da fila.

Para avaliação do cluster, utilizaremos o Coeficiente de Silhueta:

In [52]:
from sklearn.metrics import silhouette_score

faixa_quantil = np.linspace(0.02, 1, 30) ## vetor com quantis variando de 0.02 até 1
faixa_quantil

array([0.02      , 0.0537931 , 0.08758621, 0.12137931, 0.15517241,
       0.18896552, 0.22275862, 0.25655172, 0.29034483, 0.32413793,
       0.35793103, 0.39172414, 0.42551724, 0.45931034, 0.49310345,
       0.52689655, 0.56068966, 0.59448276, 0.62827586, 0.66206897,
       0.69586207, 0.72965517, 0.76344828, 0.79724138, 0.83103448,
       0.86482759, 0.89862069, 0.93241379, 0.9662069 , 1.        ])

In [43]:
valores_silhueta = []
quantil_plot = []

for quantil in faixa_quantil:
    bandwidth = estimate_bandwidth(df, quantile = quantil) ## estima a bw para cada quantil
    agrupador = MeanShift(bandwidth)
    labels = agrupador.fit_predict(df)

    if(len(np.unique(labels)) > 1 and len(np.unique(labels)) < len(df)): ## a qtd de labels deve ser maior que 1 e menor que a quantidade de dados
        media_silhueta = silhouette_score(df, labels)
        valores_silhueta.append(media_silhueta)
        quantil_plot.append(quantil) ## lista de quantis válidos

In [44]:
quantil_plot ## quantis utilizados na avaliação

[0.02,
 0.053793103448275856,
 0.08758620689655172,
 0.12137931034482759,
 0.15517241379310343,
 0.18896551724137928,
 0.22275862068965516,
 0.25655172413793104,
 0.2903448275862069,
 0.32413793103448274,
 0.3579310344827586,
 0.39172413793103444,
 0.42551724137931035,
 0.4593103448275862]

In [45]:
fig = go.Figure()
fig.add_trace(go.Scatter(x = quantil_plot, y = valores_silhueta))
fig.update_layout(dict(xaxis_title = 'Quantil', yaxis_title = 'Média Silhueta'))
fig.show()

A melhor média de silhueta é quando o quantil atinge o valor de 0.35.